# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch

[[versions]]
    version = "10.0"
    dirpath = "latest"
    url = "/latest/"
[[versions]]
    version = "9.9"
    dirpath = "9.9"
    url = "/9.9/"
    tag = "v9.9.0"
[[versions]]
    version = "9.8"
    dirpath = "9.8"
    url = "/9.8/"
    tag = "v9.8.1"
[[versions]]
    version = "9.7"
    dirpath = "9.7"
    url = "/9.7/"
    tag = "v9.7.0"
[[versions]]
    version = "Older"
    url = "https://sdk.gooddata.com/gooddata-ui/versions.html"
