# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch

[[versions]]
    version = "10.27"
    dirpath = "latest"
    url = "/latest/"
[[versions]]
    version = "10.26"
    dirpath = "10.26"
    url = "/10.26/"
[[versions]]
    version = "10.25"
    dirpath = "10.25"
    url = "/10.25/"
[[versions]]
    version = "10.24"
    dirpath = "10.24"
    url = "/10.24/"
[[versions]]
    version = "Older"
    url = "https://sdk.gooddata.com/gooddata-ui/versions.html"
