name: check

on:
  pull_request:
    branches:
      - master
      - release

concurrency:
  group: check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-validate-stage:
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    name: build-validate-stage
    uses: ./.github/workflows/rw-rush-build-basic-checks.yml
    with:
      target-branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit

  ready-to-merge:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    if: ${{ !cancelled() }}
    needs:
      - build-validate-stage
    steps:
      - name: Check if needed jobs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
