name: Doc ~ Update ApiDocs
on:
    workflow_dispatch:
jobs:
    update-apidocs-next:
        uses: ./.github/workflows/rw-doc-release-apidocs.yml
        permissions:
            contents: write
            id-token: write
        secrets: inherit
        with:
            source-branch: "master"
            version: "Next"
            is-new-latest: false
    update-apidocs-version:
        uses: ./.github/workflows/rw-doc-release-apidocs.yml
        permissions:
            contents: write
            id-token: write
        secrets: inherit
        with:
            source-branch: "release"
            version: "9.7.0"
            is-new-latest: true
